name: Arktox
description: "Eine App basierend auf Archiv"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_phoenix: ^1.1.1
  http: ^1.2.1
  intl: ^0.19.0
  mysql_client: ^0.0.27
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/default_banner.jpg
